/**
 * This file was automatically generated by generate-schemas.ts
 * ***Do not touch!***
 */
import { z } from "zod";

export const PostApiV1AuthRegisterRequestSchema = z.object({
	name: z.string(),
	email: z.string().email(),
	password: z.string(),
});

export const PostApiV1AuthLoginRequestSchema = z.object({
	email: z.string().email(),
	password: z.string(),
});

export const PostApiV1AuthForgotPasswordRequestSchema =
	z.object({ email: z.string().email() });

export const PatchApiV1UsersByIdRequestSchema = z.object({
	name: z.string().optional(),
	email: z.string().email().optional(),
});

export const PostApiV1ProjectsRequestSchema = z.object({
	name: z.string().optional(),
});
