/**
 * This file was automatically generated by generate-schemas.ts
 * ***Do not touch!***
 */
import {z} from "zod";

export const PostApiV1AuthLoginRequestSchema = z.object({ "email": z.string().email(), "password": z.string() });

export const PostApiV1AuthForgotPasswordRequestSchema = z.object({ "email": z.string().email(), user: z.object({
  name: z.string()
}) });
