/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const fullWidth: string;
const textCenter: string;
const form: string;
const label: string;
const alreadyHaveAnAccount: string;

export {
	fullWidth,
	textCenter,
	form,
	label,
	alreadyHaveAnAccount
};

export default {
	fullWidth,
	textCenter,
	form,
	label,
	alreadyHaveAnAccount
};
