/**
 * A utility script for generating request schemas
 * in zod from a given openapi spec.
 */

import jsonSchemaToZod from "json-schema-to-zod";
import { parseArgs } from "node:util";
import type { OpenAPIV3 } from "openapi-types";

(async () => {
	const before = performance.now();

	const { positionals, values } = parseArgs({
		args: Bun.argv.slice(2),
		options: {
			input: {
				type: "string",
				short: "i",
			},
			output: {
				type: "string",
				short: "o",
			},
		},
		allowPositionals: true,
	});

	const input = values.input ?? positionals[0];
	const output = values.output ?? positionals[1];

	if (!input) {
		throw new Error("Please provide an input file/url.");
	}

	if (!output) {
		throw new Error("Please provide an output file/url.");
	}

	const formatDuration = (totalMs: number) => {
		let ms = totalMs;
		if (ms < 0) {
			ms = -ms;
		}
		const time = {
			d: Math.floor(ms / 86400000),
			h: Math.floor(ms / 3600000) % 24,
			m: Math.floor(ms / 60000) % 60,
			s: Math.floor(ms / 1000) % 60,
			ms: Math.floor(ms) % 1000,
		};
		return Object.entries(time)
			.filter((val) => val[1] !== 0)
			.map(([unit, amount]) => `${amount}${unit}`)
			.join(", ");
	};

	const exit = (message: string) => {
		const elapsed = performance.now() - before;
		// biome-ignore lint/suspicious/noConsole: We can do a little loggin' here 😎
		console.log(
			`🔥 ${message} [${formatDuration(elapsed)}]`,
		);
		process.exit();
	};

	let text: string;
	if (input.match(/https?:\/\//)) {
		const response = await fetch(input);
		text = await response.text();
	} else {
		text = await Bun.file(input).text();
	}

	const hasher = new Bun.CryptoHasher("sha256");
	hasher.update(text);
	const hash = hasher.digest("hex").slice(0, 8);
	const json: OpenAPIV3.Document = JSON.parse(text);

	const capitaliseAscii = (x: string) =>
		x[0].toUpperCase() + x.slice(1);

	const exists = await Bun.file(output).exists();
	let contents = "";
	if (exists) {
		contents = await Bun.file(output).text();
	}

	const firstLine = contents.split(/\r*\n/)[0];
	const noChangesInSpecFile = firstLine.startsWith(
		`// ${hash}`,
	);
	if (noChangesInSpecFile) {
		exit(`${input} (no changes)`);
	}

	const document = json as OpenAPIV3.Document;
	const validators: string[] = [];

	for (const [name, schema] of Object.entries(
		document.components?.schemas ?? {},
	)) {
		if ("$ref" in schema) {
			continue;
		}

		const capitalised = capitaliseAscii(name);
		const formattedName = `${capitalised}Schema`;

		validators.push(`
export const ${formattedName} = ${jsonSchemaToZod(schema)};
export type ${capitalised} = z.infer<typeof ${formattedName}>;`);
	}

	const header = `
// ${hash}
// eslint-disable
// prettier-ignore
// @ts-nocheck
/**
 * This file was automatically generated by generate-schemas.ts
 * ***Do not touch!***
 */
import {z} from "zod";
`.trim();

	await Bun.file(output).write(
		`${header}\n${validators.join("\n")}`,
	);

	exit(`${input} → ${output}`);
})();
