/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const textCenter: string;
const form: string;
const label: string;

export {
	textCenter,
	form,
	label
};

export default {
	textCenter,
	form,
	label
};
