/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const layout: string;
const gridMain: string;

export {
	layout,
	gridMain
};

export default {
	layout,
	gridMain
};
