/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const header: string;
const row: string;
const link: string;
const active: string;

export {
	header,
	row,
	link,
	active
};

export default {
	header,
	row,
	link,
	active
};
