/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const sizeSmall: string;
const sizeMedium: string;
const sizeLarge: string;

export {
	sizeSmall as "size-small",
	sizeSmall,
	sizeMedium as "size-medium",
	sizeMedium,
	sizeLarge as "size-large",
	sizeLarge
};

export default {
	"size-small": sizeSmall,
	sizeSmall,
	"size-medium": sizeMedium,
	sizeMedium,
	"size-large": sizeLarge,
	sizeLarge
};
