/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const loadingIndicator: string;

export {
	loadingIndicator
};

export default {
	loadingIndicator
};
