/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const button: string;
const input: string;
const link: string;
const title: string;
const heading: string;
const subheading: string;

export {
	button,
	input,
	link,
	title,
	heading,
	subheading
};

export default {
	button,
	input,
	link,
	title,
	heading,
	subheading
};
