name: Build

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i --frozen-lockfile
      - run: bun run build
